# Generated by Django 4.1.4 on 2023-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='mobile',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
